# fly.toml app configuration file generated for law-archive-data on 2023-08-20T20:37:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "law-archive-data"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
