services:
  app:
    build:
      context: ../
      dockerfile: ./docker/prod.Dockerfile
    container_name: lacunadb
    restart: unless-stopped
    networks:
      - caddy_network
    environment:
      DATASETTE_MATOMO_SERVER_URL: //analytics.huey.xyz/
      DATASETTE_MATOMO_SITE_ID: 1

networks:
  caddy_network:
    name: caddy_network
    external: true
