name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'input/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 1.3.185
      - name: Run tests
        run: bb --main test.input.utils.date-test