name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'input/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          lfs: true
          fetch-depth: 0
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.6.0
        with:
          babashka-version: 1.3.190
      - name: clj-kondo
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          clj-kondo: 2023.10.20
      - name: Lint code
        run: clj-kondo --lint input scripts test
      - name: Run tests
        run: bb --main test.input.utils.date-test