name: Deploy Datasette

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'data/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: rebuild and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.TAILSCALE_DEPLOY_TARGET }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_DIRECTORY }} && \
            git pull --rebase && \
            devenv shell build-db && \
            devenv shell build-frontend && \
            devenv shell prod-datasette
