name: Obtain latest fc-judgments data

on:
  workflow_dispatch:
  schedule:
    - cron: '41 18 * * *' # 6.41AM GMT+8

jobs:
  sc:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v15
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Fetch latest data
      run: devenv shell fetch-fc-judgments
    - name: Commit and push if it changed
      run: devenv shell automated-git-push fc-judgments
        