name: Obtain latest fc-judgments data

on:
  workflow_dispatch:
  schedule:
    - cron: '41 18 * * *' # 6.41AM GMT+8

jobs:
  sc:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Setup Babashka
      uses: turtlequeue/setup-babashka@v1.6.0
      with:
        babashka-version: 1.3.190
    - name: Fetch latest data
      run: bb --main input.judgments.fc-judgments
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated update"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(TZ='Asia/Singapore' date)
        git commit -m "Latest fc-judgments data: ${timestamp}" || exit 0
        git pull --rebase
        git push