name: Obtain latest SC data

on:
  workflow_dispatch:
  schedule:
    - cron: '4 21 * * 1' # 9.04PM GMT+8 every Monday

jobs:
  sc:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
        token: ${{ secrets.PAT }}
    - name: Setup Babashka
      uses: turtlequeue/setup-babashka@v1.5.2
      with:
        babashka-version: 1.3.188
    - name: Fetch latest data
      run: bb --main input.sc.run
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated update"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(TZ='Asia/Singapore' date)
        git commit -m "Latest SC data: ${timestamp}" || exit 0
        git pull --rebase
        git push