name: Obtain latest stc-judgments data

on:
  workflow_dispatch:
  schedule:
    - cron: '15 15 * * 1' # 11.15PM GMT+8 every Monday

jobs:
  sc:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Babashka
      uses: turtlequeue/setup-babashka@v1.5.2
      with:
        babashka-version: 1.3.186
    - name: Fetch latest data
      run: bb --main input.judgments.stc-judgments
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated update"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(TZ='Asia/Singapore' date)
        git commit -m "Latest stc-judgments data: ${timestamp}" || exit 0
        git pull --rebase
        git push