name: Obtain latest telco-fbo data

on:
  workflow_dispatch:
  schedule:
    - cron: '12 20 * * 0,1,3,5' # 2.12AM GMT+8 every Sunday, Monday, Wednesday, and Friday

jobs:
  telco-fbo:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v15
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Fetch latest data
      run: devenv shell fetch-telco-fbo
    - name: Commit and push if it changed
      run: devenv shell automated-git-push telco-fbo