name: Obtain latest telco-fbo data

on:
  workflow_dispatch:
  schedule:
    - cron: '12 20 * * 0,1,3,5' # 2.12AM GMT+8 every Sunday, Monday, Wednesday, and Friday

jobs:
  telco-fbo:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Setup Babashka
      uses: turtlequeue/setup-babashka@v1.7.0
      with:
        babashka-version: 1.3.190
    - name: Fetch latest data
      run: bb --main input.telco.fbo
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated update"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(TZ='Asia/Singapore' date)
        git commit -m "Latest telco-fbo data: ${timestamp}" || exit 0
        git pull --rebase
        git push